package businessLogicImpl.managerBLImpl;

import businessLogicService.managerBLService.OrganizationManagementBLService;

public class OrganizationManagementBLImpl implements OrganizationManagementBLService {

}
